// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsmqYtsDVMffi2tignD6VrriGz-BCEJ1w',
    appId: '1:311675969849:web:8013e1fecb1839221a48e8',
    messagingSenderId: '311675969849',
    projectId: 'todo-77dc1',
    authDomain: 'todo-77dc1.firebaseapp.com',
    storageBucket: 'todo-77dc1.appspot.com',
    measurementId: 'G-1Z6FWJ1DSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2bk57GSYR02W2wpxOJbDsL8EEKwGg6OQ',
    appId: '1:311675969849:android:632281c2241572691a48e8',
    messagingSenderId: '311675969849',
    projectId: 'todo-77dc1',
    storageBucket: 'todo-77dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB1hjuwCzTNQBiY8TsT3X7QitDmyY-26o',
    appId: '1:311675969849:ios:d5dd8b386a8b360c1a48e8',
    messagingSenderId: '311675969849',
    projectId: 'todo-77dc1',
    storageBucket: 'todo-77dc1.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB1hjuwCzTNQBiY8TsT3X7QitDmyY-26o',
    appId: '1:311675969849:ios:d5dd8b386a8b360c1a48e8',
    messagingSenderId: '311675969849',
    projectId: 'todo-77dc1',
    storageBucket: 'todo-77dc1.appspot.com',
    iosBundleId: 'com.example.myApp',
  );
}
